YAML: Added failure error code when latest version of Flatbed.Dialog.Lite is not found

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -184,7 +184,6 @@ jobs:
       run: dotnet restore ${{env.SolutionName}}.sln
     - name: Building .NET
       run: dotnet build ${{needs.detect_frameworks.outputs.net_project_path}} --configuration Release --no-restore /p:OutputPath="${{github.workspace}}/bin" /p:DocumentationFile="${{github.workspace}}/bin/${{env.SolutionName}}.xml" /p:SignAssembly=true /p:Version=${{needs.version.outputs.new_version}} /p:AssemblyOriginatorKeyFile="${{steps.sign_key_file.outputs.filePath}}"
-    #TODO: I need to find a better approach to sign output files without explicitly specify filename and extension
     - name: Signing portable executables
       uses: dlemstra/code-sign-action@v1
       with:
@@ -192,6 +191,7 @@ jobs:
         password: '${{secrets.SIGN_PE_PASSWORD}}'
         recursive: false
         files: |
+          # Applying PE certificate to the result PE file (We can't add certificate to all PE files because there could be many assemblies from NuGet packages)
           ${{github.workspace}}\bin\${{env.SolutionName}}.dll
     - name: Deploying artifacts
       uses: actions/upload-artifact@v4
@@ -224,8 +224,8 @@ jobs:
         LATEST_VERSION=$(curl -s -H "Authorization: token ${{secrets.DEPLOYMENT_TOKEN}}" "https://api.github.com/repos/DKorablin/Flatbed.Dialog.Lite/releases/latest" | jq -r .tag_name)
         
         if [ "$LATEST_VERSION" = "null" ] || [ -z "$LATEST_VERSION" ]; then
-          echo "Could not find the latest release for DKorablin/Flatbed.Dialog.Lite. Skipping merge."
-          exit 0
+          echo "Error: Could not find the latest release for DKorablin/Flatbed.Dialog.Lite. Skipping merge."
+          exit 1
         fi
         echo "Latest Flatbed.Dialog.Lite version is $LATEST_VERSION"
 
@@ -247,6 +247,7 @@ jobs:
           echo "Checking for asset $ASSET_NAME"
           HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -L -H "Authorization: token ${{ secrets.DEPLOYMENT_TOKEN }}" "$DOWNLOAD_URL")
           
+          # Downloading asset and unzip it into current folder
           if [ "$HTTP_STATUS" -eq 200 ]; then
             echo "Downloading asset..."
             curl -s -L -H "Authorization: token ${{ secrets.DEPLOYMENT_TOKEN }}" -H "Accept: application/octet-stream" -o "${ASSET_NAME}" "$DOWNLOAD_URL"
@@ -254,11 +255,13 @@ jobs:
             unzip -o "${ASSET_NAME}" -d "$dir_name"
             rm "${ASSET_NAME}"
           else
-            echo "Warning: Could not download asset ${ASSET_NAME}. HTTP status: $HTTP_STATUS. It may not exist for this .NET version."
+            echo "Error: Could not download asset ${ASSET_NAME}. HTTP status: $HTTP_STATUS. It may not exist for this .NET version."
+            exit 1
           fi
         done
     - name: Zipping individual artifacts
       run: |
+        # Packing each subdirectory into different release asset
         cd ${{github.workspace}}/bin
         for dir in */; do
           dir_name="${dir%/}"
@@ -268,6 +271,7 @@ jobs:
     - name: Deploying GitHub release
       uses: ncipollo/release-action@v1
       with:
+        # Creating deployment release with from all packed zip files
         artifacts: ${{github.workspace}}/bin/*.zip
         tag: ${{needs.version.outputs.new_tag}}
         name: Auto ${{needs.version.outputs.new_tag}}
@@ -287,7 +291,6 @@ jobs:
         (needs.build_net_framework.result == 'skipped' || needs.build_net_framework.result == 'success') &&
         (needs.build_net.result == 'skipped' || needs.build_net.result == 'success')
     runs-on: windows-latest
-
     steps:
     - name: Checkout nessesary files from repository
       uses: actions/checkout@v4
